#!/usr/bin/env node
const { execSync } = require('child_process')
const { cwd } = require('process')

const { containers } = require(`${cwd()}/containers/manifest.json`)

// 循环构建
for (const container of containers) {
  const variants = gengerateVariants(container)
  for (variant of variants) {
    const file = `containers/${container}/Dockerfile`
    const tag = `ghcr.io/coajs/${container}:${variant}`
    console.warn()
    console.warn(`开始构建 ${tag}`)
    console.warn()
    execSync(
      `docker build -f ${file} -t ${tag} --build-arg VARIANT=${variant} .`,
      { stdio: 'inherit' }
    )
  }
}

// 获取所有的 variant
function gengerateVariants(container) {
  const variants = ['latest']
  const definition = require(`${cwd()}/containers/${container}/definition-manifest.json`)
  const manifest = require(`${cwd()}/${definition.manifest}`)
  const versions = manifest.definitionVersion.split('.')
  for (const variant of definition.variants.sort()) {
    variants.push(variant)
    const prev = []
    for (const version of versions) {
      prev.push(version)
      variants.push(`${prev.join('.')}-${variant}`)
    }
  }
  return variants.reverse()
}
