name: Sync
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Init
        run: |
          echo ${{ secrets.AEX_TOKEN }} | docker login ghcr.io -u adaex --password-stdin
          git config --global user.name Aex
          git config --global user.email adaex@qq.com

      - name: Setup
        run: script/setup

      - name: Sync
        run: script/sync
